FROM 172.30.1.1/common/golang:1.17.9

RUN wget https://github.com/gohugoio/hugo/releases/download/v0.98.0/hugo_0.98.0_Linux-64bit.tar.gz -O /dev/stdout  | tar -zxvf - && \
    mv hugo /usr/bin/ && \
    rm -f LICENSE README.md



